### ISSUE TITLE
Stromdaten Tibber - Log normal?

### ISSUE THREAD

**Issue by Tobi0484** [solectrus/senec-charger#156]
Ist es normal, dass im Log folgendes ausgegeben wird:

#11 - 2024-09-16 19:51:16 +0200
 Grid power not cheap, nothing to do
 No prices found between 2024-09-16 19:00:00 +0200 and 2024-09-17 19:00:00 +0200
 Sleeping for 3600 seconds ...

 #12 - 2024-09-16 20:51:16 +0200
 Grid power not cheap, nothing to do
 No prices found between 2024-09-16 20:00:00 +0200 and 2024-09-17 20:00:00 +0200
 Sleeping for 3600 seconds ...

 #13 - 2024-09-16 21:51:17 +0200
 Grid power not cheap, nothing to do
 No prices found between 2024-09-16 21:00:00 +0200 and 2024-09-17 21:00:00 +0200
 Sleeping for 3600 seconds ...

 #14 - 2024-09-16 22:51:17 +0200
 Grid power not cheap, nothing to do
 No prices found between 2024-09-16 22:00:00 +0200 and 2024-09-17 22:00:00 +0200
 Sleeping for 3600 seconds ...

Der Preis sieht eigentlich gar nicht schlecht aus für morgen:
![image](https://github.com/user-attachments/assets/ca9a33ae-7d09-4636-8e35-9663f759ea14)

Der Collector für Tibber hat folgenden Log:

#1 - 2024-09-16 09:51:19 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #2 - 2024-09-16 10:51:20 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #3 - 2024-09-16 11:51:20 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #4 - 2024-09-16 12:51:20 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #5 - 2024-09-16 13:51:21 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #6 - 2024-09-16 14:51:21 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #7 - 2024-09-16 15:51:21 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #8 - 2024-09-16 16:51:21 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #9 - 2024-09-16 17:51:22 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #10 - 2024-09-16 18:51:22 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #11 - 2024-09-16 19:51:22 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #12 - 2024-09-16 20:51:22 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #13 - 2024-09-16 21:51:23 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

 #14 - 2024-09-16 22:51:23 +0200
   Fetching prices from Tibber ... OK
   Pushing prices to InfluxDB ... OK
   Sleeping for 3600 seconds ...

**Comment by ledermann** [comment]
Die Meldung `No prices found between 2024-09-16 19:00:00 +0200 and 2024-09-17 19:00:00 +0200` ist nicht richtig so.

Meine Vermutung: Der Tibber-Collector schreibt die Preise an eine andere Stelle, als sie der SENEC-Charger erwartet. Wichtig ist, dass folgende zwei Variablen identische Werte haben:

- Tibber-Collector: `INFLUX_MEASUREMENT`
- SENEC-Charger: `INFLUX_MEASUREMENT_PRICES`

Gleiches gilt für das Bucket (`INFLUX_BUCKET`).

Beide Tools geben übrigens die verwendeten Buckets/Measurements beim Start an.

Wenn dir das nicht hilft, dann poste bitte mal deine `compose.yml` und `.env`
