### ISSUE TITLE
(Konfigurations-/Verständnisfehler?) Tibberpreis wird nicht in Solectrus-Oberfläche übernommen

### ISSUE THREAD

**Issue by Daedalus3** [solectrus/senec-charger#30]
(Erst einmal danke für dieses großartige Tool. Danke, dass du deine Freizeit dafür opferst, Senecs GUI-Böcke auszumerzen und deren App weit weit weit zu übertreffen.)

Ich habe einige Verständnisfrage und bitte um Gnade, den Tracker zu missbrauchen :). Ich habe heute zum ersten mal versucht, den Senec-Charger und damit auch Tibber einzubinden. Auf den ersten Blick würde ich anhand der Logs behaupten, dass es geglückt ist, allerdings zeigt Solectrus selbst nach wie vor nur den statisch hinterlegten Preis von 0,2545 €. Ist das korrekt -oder  das Zeichen dafür, dass die Installation doch nicht so ganz geglückt ist?

**Comment by ledermann** [comment]
Danke für die Blumen :) 

Deine Beobachtung ist übrigens richtig: Die Berechnung der Stromkosten innerhalb von SOLECTRUS wird durch den SENEC-Charger nicht beeinflusst. Das ist noch ein ganz anderes Thema, siehe hier:
https://github.com/solectrus/solectrus/issues/2150

Derzeitig können Strompreise zwar in SOLECTRUS erfasst werden (im Menü "Einstellungen"), aber nur die klassischen, nicht die dynamischen.
