### ISSUE TITLE
Anleitung Senec-Charger, Tibber Integration

### ISSUE THREAD

**Issue by Nemo3006** [solectrus/senec-charger#33]
Hallo!
Dank deiner großen Hilfe habe ich gestern Abend endlich Solectrus wieder ans Laufen bekommen. Nun würde ich das preisbasierte Laden des Speichers per Tibber integrieren. Gibt es dafür auch irgendwo eine Step by step Anleitung?

Viele Grüße
Daniel

**Comment by ledermann** [comment]
Eine wirkliche Anleitung gibt es noch nicht, aber du kannst dich an der [docker-compose.yml](https://github.com/solectrus/senec-charger/blob/develop/docker-compose.yml) und [.env](https://github.com/solectrus/senec-charger/blob/develop/.env.example) in diesem Repo orientieren.

Das heißt: Die beiden Services (`tibber-collector` und `senec-charger`) in deiner `docker-compose.yml` ergänzen, dann die `.env` um die neuen Variablen erweitern. Container starten. Fertig.

Wichtig: Unbedingt in der ersten Zeit die Logs der beiden neuen Container genau im Auge behalten. Nur dort steht, ob und was überhaupt passiert.

**Comment by ledermann** [comment]
Mittlerweile gibt es das hier:

https://docs.solectrus.de/referenz/senec-charger/
https://docs.solectrus.de/referenz/tibber-collector/
