### ISSUE TITLE
Konfiguration % Schwellwert

### ISSUE THREAD

**Issue by esusxunil** [solectrus/senec-charger#54]
Hallo,

ich habe den Tibber Collector und den Senec Charger integriert bekommen und aktuell im Dry Run Modus laufen.

Im Blog Artikel hatte ich gesehen, dass man den Prozentschwellwert (im Beispiel 70%) konfigurieren kann, ich habe aber weder in der YAML noch der .env Datei irgendwas dazu gefunden.

Kann man den Wert schon anpassen oder ist das noch geplant?

**Comment by ledermann** [comment]
Es handelt sich um [diese Zeilen](https://github.com/solectrus/senec-charger/blob/develop/.env.example#L8-L9):

```env
# Maximum average price per kWh compared to average price in the near future (up to 24 hours)
CHARGER_PRICE_MAX=70
```

Jaja, [naming is one of the hardest things in computer science](https://martinfowler.com/bliki/TwoHardThings.html) ...
